version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: stress-test/7.4.27-zts
    container_name: stress-test-app
    tty: true
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - playlumendice_app-network

networks:
  playlumendice_app-network:
    external: true
